### ISSUE TITLE
Chapter 5: Code snippet wrong

### ISSUE THREAD

**Issue by 0c12a4c9-4c00-4211-8531-353dbff93969** [edgedb/easy-edgedb#120]
```
insert MinorVampire {
  name := 'Vampire Woman 1',
  master := assert_single(select Vampire filter .name = 'Count Dracula')
};
```

The select needs to be wrapped in parentheses. 

Tried to do a PR but the code in master is different from what's deployed on the website and the content there is different

**Comment by Dhghomon** [comment]
Looks like this has already been taken care of so will close now!
