### ISSUE TITLE
Chapter 13: Missing/Extra words in Introspective section

### ISSUE THREAD

**Issue by bryanjnelson** [edgedb/easy-edgedb#122]
![Chapter_13_—_Meet_the_new_Lucy___Easy_EdgeDB___EdgeDB](https://github.com/edgedb/easy-edgedb/assets/1914742/6db8d1a5-8db1-49b2-bbd3-2ac0bb19222b)

I believe some words or code are either missing or extra in this sentence.

**Comment by Dhghomon** [comment]
Yep, definitely a typo. Thanks! Fixed with https://github.com/edgedb/easy-edgedb/commit/a7ef0bdecbe12835da9e24833bc8073f43016186
