### ISSUE TITLE
Chapter 14 - Practice Question 5 - potential issue

### ISSUE THREAD

**Issue by bryanjnelson** [edgedb/easy-edgedb#123]
In Chapter 14, on the final practice question, the answer is given as such:

```json
{
  schema::ObjectType {
    name: 'default::MinorVampire',
    annotations: {
      schema::Annotation {
        name: 'std::description',
        @value: 'first_appearance for MinorVampire should always match last_appearance for its matching NPC type',
      },
    },
  },
}
```

However, in light of the fact that the question asks for the name of the annotation to be `note`, shouldn't

```json
name: 'std::description',
```

be

```json
name: 'std::note',
```
?

**Comment by Dhghomon** [comment]
Yes, looks like it's `default::note` as opposed to `std::description` which is for built-in annotations. Thanks!
