### ISSUE TITLE
Chapter 16

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/easy-edgedb#27]
> index on (.excerpt);

This is misguided. Indexing on a large string that probably would rarely be used in its entirety is odd. On the other hand, `index on
(.date)` seems pretty perfect. Fetching quickly some `BookExcerpt` pertaining to a specific date is a reasonable operation in this game's context.

The simple story is that indexing makes a lookup by an exact match faster than scanning everything. Although it also affects lookups by partial match with prefixes (e.g. `LIKE 'some%'` or similar) it is not so beneficial for the `excerpt` property since that is expected to contain a very large amount of text where the prefix is not necessarily what would be used for lookup.

**Comment by Dhghomon** [comment]
Okay, changed this and added your "indexing makes a lookup by an exact match faster than scanning everything." almost verbatim as it explains the concept well. (I've never had to use an index so the concept was a bit vague to me, as you can tell).
