### ISSUE TITLE
Question about the plot of Chapter 11

### ISSUE THREAD

**Issue by daichen-daisy** [edgedb/easy-edgedb#38]
> We are starting to see more and more events in the book with various characters. Some events have the three men and Dr. Van Helsing together, others have just Lucy and Dracula. 

About the above content, I am a little bit confused. Who are three men? It seems never specifically mentioned before. Does it mean the three men who are pursuing Lucy? If so,  is there really an event that happened between them and Dr. Van Helsing at the same time?

**Comment by 1st1** [comment]
@Dhghomon

**Comment by Dhghomon** [comment]
It's the three men mentioned two chapters earlier:

https://github.com/edgedb/easy-edgedb/blob/master/chapter9/index.md

They start out as her boyfriends (suitors, that is)

>Lucy has three boyfriends (named Dr. John Seward, Quincey Morris, and Arthur Holmwood), and they all want to marry her....

 until Lucy chooses one, but fortunately the three men remain friends:

> The other two men are sad, but fortunately the three men become friends with each other.

**Comment by daichen-daisy** [comment]
@Dhghomon Much thanks! I am working on the translation of this book, so I just want to clear some problems which make me confused so that I could provide the most precise translation. Now that it is truly clear enough. Thanks again. In addition, this book is really fabulous!!! It's a tutorial with a good storyteller. It's a novel way! I like it. I translate it because I hope more and more people in my country are more willing to read it without the language barrier.
