### ISSUE TITLE
Chapter 4: can we change 'date' to 'time'?

### ISSUE THREAD

**Issue by daichen-daisy** [edgedb/easy-edgedb#55]
https://github.com/edgedb/easy-edgedb/blob/9c5c0936fb14a2d1a1e8b6f56aa98e7b96f8c208/chapter4/index.md#L167-L173

Here is the definition of type `Time`. One of the properties is named `date`, but the author wanted to express `time`. It's confusing, I think. The same problem also happens in Chapter 7 and Chapter 19, because we use `Time` all the time. Do you think it is an issue? If so, I can commit another pull request and make sure that everywhere we use this type will be corrected.

**Comment by daichen-daisy** [comment]
https://github.com/edgedb/easy-edgedb/blob/9c5c0936fb14a2d1a1e8b6f56aa98e7b96f8c208/chapter4/index.md?plain=1#L167-L173

Here is the definition of type `Time`. One of the properties is named `date`, but the author wanted to express `time`. It's confusing, I think. The same problem also happens in Chapter 7 and Chapter 19, because we use `Time` all the time. Do you think it is an issue? If so, I can commit another pull request and make sure that everywhere we use this type will be corrected.

**Comment by vpetrovykh** [comment]
Thanks for pointing it out! This seems like an oversight indeed. The type should be:
```
type Time { 
  required property clock -> str; 
  property clock_time := <cal::local_time>.clock; 
  property hour := .clock[0:2]; 
} 
```
And the references should be updated. When updating `local_time` to `clock_time` make sure it's the property getting updated and not the builtin type name (in casts). If you could do a PR for this, it would be greatly appreciated.

**Comment by daichen-daisy** [comment]
I will carefully work on this and submit a PR later.
