### ISSUE TITLE
Chapter 13: a question about 'former_self'

### ISSUE THREAD

**Issue by daichen-daisy** [edgedb/easy-edgedb#56]
https://github.com/edgedb/easy-edgedb/blob/9c5c0936fb14a2d1a1e8b6f56aa98e7b96f8c208/chapter13/index.md#L22-L26

I am not sure my question is dumb or not, but I am wondering that if the `MinorVampire` always comes from an `NPC`, why not link `former_self` to `NPC` type? (now we link it to `Person`) Is it because we want to leave some flexibility to readers?

**Comment by vpetrovykh** [comment]
This is mostly to keep things simple and leave some flexibility. `Person` is used as the base type for all kinds of characters (like `Sailor` and `Crewman`). So it's used as a base type here as well.
