### ISSUE TITLE
Chapter 8: about `multi property` vs. objects

### ISSUE THREAD

**Issue by daichen-daisy** [edgedb/easy-edgedb#57]
https://github.com/edgedb/easy-edgedb/blob/9c5c0936fb14a2d1a1e8b6f56aa98e7b96f8c208/chapter8/index.md#L340

This sentence in the link makes me confused a lot. 

"Do you have a lot of duplication in property values?" If my answer is yes, then `multi link` with `constraint exclusive` won't solve my problem, because it literally REMOVED all duplicates, while I'd probably want to have duplicates in my "multi property". So, @vpetrovykh could you please help rephrase this part to make it clearer. Thanks.

I am not an English native speaker, so I guess I am a suitable person to test the readability of this book, especially, we emphasized that "Plain English (easy to understand)" is one of this book's specialties in Chapter 0. So I think my feedback might be worth considering?

**Comment by vpetrovykh** [comment]
After re-reading it I agree that this does seem very confusing. I'll need to re-write this sentence.

**Comment by vpetrovykh** [comment]
I think the intent here is to cover a use case where you want a multi properties as a proper set, but without enforcing global exclusivity that comes with `constraint exclusive`.

**Comment by vpetrovykh** [comment]
I'll use a different positive example, I think. One which we have already seen in the book. When more than one type might need to refer to the property values it's better to use objects, like we do for `places_visited`.
