### ISSUE TITLE
Chapter 15:  add `master` link into `MinorVampire` type

### ISSUE THREAD

**Issue by daichen-daisy** [edgedb/easy-edgedb#59]
https://github.com/edgedb/easy-edgedb/blob/9c5c0936fb14a2d1a1e8b6f56aa98e7b96f8c208/chapter15/index.md#L263-L281

In line 263, the author mentioned: "one way to start would be with a property called `master_name` that is just a string." but I don't see another way in the following. Also, I don't think `master_name` is meaningful and necessary in "the first one way." I guess we lost something after revising several times. I am not sure I could understand it correctly, but I want to give it a try here. Please let me know if my rephrase works.

----
To add the `master` link again, one way to start would be with a property called `master_name` that is just a string. Then we can use it to filter out the corresponding `Vampire` and assign it to a computed link named `master` as follows:

```sdl
type MinorVampire extending Person {
  link former_self -> Person;
  required single property master_name -> str;
  link master := (
    WITH master_name := .master_name
    assert_single(SELECT Vampire FILTER .name = master_name));
};
```

Note: it's a single link, so we need to add `assert_single()` (it won't work otherwise). However, it looks a little bit chubby, and we have to trust the users to input `master_name` correctly by themselves. It sounds not perfect. Therefore, there is a more simple and robust way to add `master`: to use a reverse link:

```sdl
type MinorVampire extending Person {
  link former_self -> Person;
  link master := assert_single(.<slaves[IS Vampire]);
};
```

If you still want to have a shortcut for `master_name`, you could add `property master_name := .master.name;` in the above `{}` like this:

```sdl
type MinorVampire extending Person {
  link former_self -> Person;
  link master := assert_single(.<slaves[IS Vampire]);
  property master_name := .master.name;
};
```

**Comment by Dhghomon** [comment]
Looks good (commit here https://github.com/edgedb/easy-edgedb/commit/9afb8dea25a551d72032cd935a80104180719fd2 ) and I see this one is also in the Chinese translation so no need to change anything there. Thanks!
