### ISSUE TITLE
chapter 10: function vs create function, cardinality mismatches

### ISSUE THREAD

**Issue by krt-z** [edgedb/easy-edgedb#60]
edit: I see in chapter 12 that function vs create function is sdl vs ddl. I'd been creating and dropping functions in the console to play around.

Both the main text and the exercises use `function` instead of `create function`.

The lucy() exercise shows the following answer:
```
function lucy() -> NPC
  using (
    SELECT NPC FILTER .name = 'Lucy Westenra'
  );
```

which produces `error: InvalidFunctionDefinitionError: return cardinality mismatch in function declared to return exactly one value`.

I got it to work with assert_exists and assert_single (is there a better way to assert exactly 1?):
```
create function lucy() -> NPC
.......   using (
.......     assert_exists(assert_single((SELECT NPC FILTER .name = 'Lucy Westenra')))
.......   );
```

using `set of` also works (`create function lucy() set of NPC using ...`), but that syntax is explained in exercise 2.

edit:

**Comment by Dhghomon** [comment]
Thanks for raising the issue! Have changed it to return a set of and added a note about the delegated constraint to make the example a bit more educational.

https://github.com/edgedb/easy-edgedb/commit/9227a152130b543991177c8fafd265bc977ded69
