### ISSUE TITLE
Chapter 5 code recap insertion error

### ISSUE THREAD

**Issue by FelixDobler** [edgedb/easy-edgedb#85]
In the [chapter5/code.md](https://github.com/edgedb/easy-edgedb/blob/53d9e0f8f942a399be09b4fbe01a2250d3a156e4/chapter5/code.md), the last insert 
```
INSERT MinorVampire {
  name := 'Woman 1',
  master := (SELECT Vampire Filter .name = 'Count Dracula'),
};
```
generates the error 
```
error: QueryError: possibly more than one element returned by an expression for a link 'master' declared as 'single'
```
due to the missing `assert_single` for the subquery as discussed in the `Required links` section of chapter 5.

**Comment by Dhghomon** [comment]
Thanks for raising the issue! Added a fix to this branch so will close now: https://github.com/edgedb/easy-edgedb/commit/3aa19233c11c599ff9262aab0d9116e66709a90e
